---
channel: edge
addons:
  plex-apsw:
    repository: barisozdag/addon-plex
    target: plex
    image: ghcr.io/barisozdag/plex-apsw/{arch}
  kitana:
    repository: barisozdag/addon-kitana
    target: kitana
    image: ghcr.io/barisozdag/kitana/{arch}
  resiliosync:
    repository: barisozdag/addon-resiliosync
    target: resiliosync
    image: ghcr.io/barisozdag/resiliosync/{arch}
  deluge:
    repository: barisozdag/addon-deluge
    target: deluge
    image: ghcr.io/barisozdag/deluge/{arch}
  transmission:
    repository: barisozdag/addon-transmission
    target: transmission
    image: ghcr.io/barisozdag/transmission/{arch}
  cloudcmd:
    repository: barisozdag/addon-cloudcmd
    target: cloudcmd
    image: ghcr.io/barisozdag/cloudcmd/{arch}
