name: Autossh
version: 2b88ade
slug: autossh
description: Automatically connect to a ssh server for forwarding ports
url: https://github.com/barisozdag/addons-autossh
codenotary: baris@ozdag.net
init: false
arch:
- armv7
- armhf
- amd64
- aarch64
- i386
host_network: true
map:
- addon_config:rw
options:
  hostname: ''
  ssh_port: '22'
  username: autossh
  remote_forwarding:
  - 127.0.0.1:8123:172.17.0.1:8123
  local_forwarding:
  - ''
  other_ssh_options: -v
  monitor_port: '0'
  gatetime: '30'
schema:
  hostname: str
  ssh_port: int
  username: str
  remote_forwarding:
  - str
  local_forwarding:
  - str
  other_ssh_options: str
  monitor_port: int
  gatetime: int
image: ghcr.io/barisozdag/autossh/{arch}
