name: CloudCMD
version: 1.0.3
slug: cloudcmd
description: Cloud Commander a file manager for the web with console and editor.
url: https://github.com/barisozdag/addon-cloudcmd
codenotary: baris@ozdag.net
webui: http://[HOST]:[PORT:8000]
panel_icon: mdi:file-search
startup: services
init: false
arch:
- aarch64
- amd64
map:
- homeassistant_config:rw
- addon_config:rw
- addons:rw
- backup:rw
- share:rw
- media:rw
- all_addon_configs:rw
- ssl
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/barisozdag/cloudcmd/{arch}
